---
- name: Create portainer volume
  become: true
  community.docker.docker_volume:
    name: portainer_data
    state: present

- name: Deploy portainer
  become: true
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce
    state: started
    pull: true
    restart_policy: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
