---
- name: Install dependencies (ca-certificates, curl)
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Ensure /etc/apt/keyrings directory exists
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable"
    codename: docker
    update_cache: true
    state: present

- name: Install Docker packages
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Testing Docker installation
  become: true
  community.docker.docker_container:
    name: hello-world
    image: hello-world
    state: started
    pull: true

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable Docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  notify:
    - Create portainer volume
    - Deploy portainer
